// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/kedr891/cs-parser/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MockPriceAnalytics is an autogenerated mock type for the PriceAnalytics type
type MockPriceAnalytics struct {
	mock.Mock
}

type MockPriceAnalytics_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPriceAnalytics) EXPECT() *MockPriceAnalytics_Expecter {
	return &MockPriceAnalytics_Expecter{mock: &_m.Mock}
}

// InvalidateMarketOverview provides a mock function with given fields: ctx
func (_m *MockPriceAnalytics) InvalidateMarketOverview(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for InvalidateMarketOverview")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPriceAnalytics_InvalidateMarketOverview_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InvalidateMarketOverview'
type MockPriceAnalytics_InvalidateMarketOverview_Call struct {
	*mock.Call
}

// InvalidateMarketOverview is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPriceAnalytics_Expecter) InvalidateMarketOverview(ctx interface{}) *MockPriceAnalytics_InvalidateMarketOverview_Call {
	return &MockPriceAnalytics_InvalidateMarketOverview_Call{Call: _e.mock.On("InvalidateMarketOverview", ctx)}
}

func (_c *MockPriceAnalytics_InvalidateMarketOverview_Call) Run(run func(ctx context.Context)) *MockPriceAnalytics_InvalidateMarketOverview_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockPriceAnalytics_InvalidateMarketOverview_Call) Return(_a0 error) *MockPriceAnalytics_InvalidateMarketOverview_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPriceAnalytics_InvalidateMarketOverview_Call) RunAndReturn(run func(context.Context) error) *MockPriceAnalytics_InvalidateMarketOverview_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTrending provides a mock function with given fields: ctx, event
func (_m *MockPriceAnalytics) UpdateTrending(ctx context.Context, event *models.PriceUpdateEvent) error {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTrending")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.PriceUpdateEvent) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPriceAnalytics_UpdateTrending_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTrending'
type MockPriceAnalytics_UpdateTrending_Call struct {
	*mock.Call
}

// UpdateTrending is a helper method to define mock.On call
//   - ctx context.Context
//   - event *models.PriceUpdateEvent
func (_e *MockPriceAnalytics_Expecter) UpdateTrending(ctx interface{}, event interface{}) *MockPriceAnalytics_UpdateTrending_Call {
	return &MockPriceAnalytics_UpdateTrending_Call{Call: _e.mock.On("UpdateTrending", ctx, event)}
}

func (_c *MockPriceAnalytics_UpdateTrending_Call) Run(run func(ctx context.Context, event *models.PriceUpdateEvent)) *MockPriceAnalytics_UpdateTrending_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.PriceUpdateEvent))
	})
	return _c
}

func (_c *MockPriceAnalytics_UpdateTrending_Call) Return(_a0 error) *MockPriceAnalytics_UpdateTrending_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPriceAnalytics_UpdateTrending_Call) RunAndReturn(run func(context.Context, *models.PriceUpdateEvent) error) *MockPriceAnalytics_UpdateTrending_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPriceAnalytics creates a new instance of MockPriceAnalytics. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPriceAnalytics(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPriceAnalytics {
	mock := &MockPriceAnalytics{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
