// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	time "time"

	models "github.com/kedr891/cs-parser/internal/models"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockSkinStorage is an autogenerated mock type for the SkinStorage type
type MockSkinStorage struct {
	mock.Mock
}

type MockSkinStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSkinStorage) EXPECT() *MockSkinStorage_Expecter {
	return &MockSkinStorage_Expecter{mock: &_m.Mock}
}

// CreateSkin provides a mock function with given fields: ctx, skin
func (_m *MockSkinStorage) CreateSkin(ctx context.Context, skin *models.Skin) error {
	ret := _m.Called(ctx, skin)

	if len(ret) == 0 {
		panic("no return value specified for CreateSkin")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Skin) error); ok {
		r0 = rf(ctx, skin)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSkinStorage_CreateSkin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSkin'
type MockSkinStorage_CreateSkin_Call struct {
	*mock.Call
}

// CreateSkin is a helper method to define mock.On call
//   - ctx context.Context
//   - skin *models.Skin
func (_e *MockSkinStorage_Expecter) CreateSkin(ctx interface{}, skin interface{}) *MockSkinStorage_CreateSkin_Call {
	return &MockSkinStorage_CreateSkin_Call{Call: _e.mock.On("CreateSkin", ctx, skin)}
}

func (_c *MockSkinStorage_CreateSkin_Call) Run(run func(ctx context.Context, skin *models.Skin)) *MockSkinStorage_CreateSkin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Skin))
	})
	return _c
}

func (_c *MockSkinStorage_CreateSkin_Call) Return(_a0 error) *MockSkinStorage_CreateSkin_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSkinStorage_CreateSkin_Call) RunAndReturn(run func(context.Context, *models.Skin) error) *MockSkinStorage_CreateSkin_Call {
	_c.Call.Return(run)
	return _c
}

// GetPopularSkins provides a mock function with given fields: ctx, limit
func (_m *MockSkinStorage) GetPopularSkins(ctx context.Context, limit int) ([]models.Skin, error) {
	ret := _m.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetPopularSkins")
	}

	var r0 []models.Skin
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]models.Skin, error)); ok {
		return rf(ctx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []models.Skin); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Skin)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSkinStorage_GetPopularSkins_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPopularSkins'
type MockSkinStorage_GetPopularSkins_Call struct {
	*mock.Call
}

// GetPopularSkins is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
func (_e *MockSkinStorage_Expecter) GetPopularSkins(ctx interface{}, limit interface{}) *MockSkinStorage_GetPopularSkins_Call {
	return &MockSkinStorage_GetPopularSkins_Call{Call: _e.mock.On("GetPopularSkins", ctx, limit)}
}

func (_c *MockSkinStorage_GetPopularSkins_Call) Run(run func(ctx context.Context, limit int)) *MockSkinStorage_GetPopularSkins_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockSkinStorage_GetPopularSkins_Call) Return(_a0 []models.Skin, _a1 error) *MockSkinStorage_GetPopularSkins_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSkinStorage_GetPopularSkins_Call) RunAndReturn(run func(context.Context, int) ([]models.Skin, error)) *MockSkinStorage_GetPopularSkins_Call {
	_c.Call.Return(run)
	return _c
}

// GetPriceHistory provides a mock function with given fields: ctx, skinID, period
func (_m *MockSkinStorage) GetPriceHistory(ctx context.Context, skinID uuid.UUID, period models.PriceStatsPeriod) ([]models.PriceHistory, error) {
	ret := _m.Called(ctx, skinID, period)

	if len(ret) == 0 {
		panic("no return value specified for GetPriceHistory")
	}

	var r0 []models.PriceHistory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, models.PriceStatsPeriod) ([]models.PriceHistory, error)); ok {
		return rf(ctx, skinID, period)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, models.PriceStatsPeriod) []models.PriceHistory); ok {
		r0 = rf(ctx, skinID, period)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.PriceHistory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, models.PriceStatsPeriod) error); ok {
		r1 = rf(ctx, skinID, period)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSkinStorage_GetPriceHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPriceHistory'
type MockSkinStorage_GetPriceHistory_Call struct {
	*mock.Call
}

// GetPriceHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - skinID uuid.UUID
//   - period models.PriceStatsPeriod
func (_e *MockSkinStorage_Expecter) GetPriceHistory(ctx interface{}, skinID interface{}, period interface{}) *MockSkinStorage_GetPriceHistory_Call {
	return &MockSkinStorage_GetPriceHistory_Call{Call: _e.mock.On("GetPriceHistory", ctx, skinID, period)}
}

func (_c *MockSkinStorage_GetPriceHistory_Call) Run(run func(ctx context.Context, skinID uuid.UUID, period models.PriceStatsPeriod)) *MockSkinStorage_GetPriceHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(models.PriceStatsPeriod))
	})
	return _c
}

func (_c *MockSkinStorage_GetPriceHistory_Call) Return(_a0 []models.PriceHistory, _a1 error) *MockSkinStorage_GetPriceHistory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSkinStorage_GetPriceHistory_Call) RunAndReturn(run func(context.Context, uuid.UUID, models.PriceStatsPeriod) ([]models.PriceHistory, error)) *MockSkinStorage_GetPriceHistory_Call {
	_c.Call.Return(run)
	return _c
}

// GetSkinBySlug provides a mock function with given fields: ctx, slug
func (_m *MockSkinStorage) GetSkinBySlug(ctx context.Context, slug string) (*models.Skin, error) {
	ret := _m.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for GetSkinBySlug")
	}

	var r0 *models.Skin
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Skin, error)); ok {
		return rf(ctx, slug)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Skin); ok {
		r0 = rf(ctx, slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Skin)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSkinStorage_GetSkinBySlug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSkinBySlug'
type MockSkinStorage_GetSkinBySlug_Call struct {
	*mock.Call
}

// GetSkinBySlug is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
func (_e *MockSkinStorage_Expecter) GetSkinBySlug(ctx interface{}, slug interface{}) *MockSkinStorage_GetSkinBySlug_Call {
	return &MockSkinStorage_GetSkinBySlug_Call{Call: _e.mock.On("GetSkinBySlug", ctx, slug)}
}

func (_c *MockSkinStorage_GetSkinBySlug_Call) Run(run func(ctx context.Context, slug string)) *MockSkinStorage_GetSkinBySlug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSkinStorage_GetSkinBySlug_Call) Return(_a0 *models.Skin, _a1 error) *MockSkinStorage_GetSkinBySlug_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSkinStorage_GetSkinBySlug_Call) RunAndReturn(run func(context.Context, string) (*models.Skin, error)) *MockSkinStorage_GetSkinBySlug_Call {
	_c.Call.Return(run)
	return _c
}

// GetSkinStatistics provides a mock function with given fields: ctx, skinID
func (_m *MockSkinStorage) GetSkinStatistics(ctx context.Context, skinID uuid.UUID) (*models.SkinStatistics, error) {
	ret := _m.Called(ctx, skinID)

	if len(ret) == 0 {
		panic("no return value specified for GetSkinStatistics")
	}

	var r0 *models.SkinStatistics
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.SkinStatistics, error)); ok {
		return rf(ctx, skinID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.SkinStatistics); ok {
		r0 = rf(ctx, skinID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.SkinStatistics)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, skinID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSkinStorage_GetSkinStatistics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSkinStatistics'
type MockSkinStorage_GetSkinStatistics_Call struct {
	*mock.Call
}

// GetSkinStatistics is a helper method to define mock.On call
//   - ctx context.Context
//   - skinID uuid.UUID
func (_e *MockSkinStorage_Expecter) GetSkinStatistics(ctx interface{}, skinID interface{}) *MockSkinStorage_GetSkinStatistics_Call {
	return &MockSkinStorage_GetSkinStatistics_Call{Call: _e.mock.On("GetSkinStatistics", ctx, skinID)}
}

func (_c *MockSkinStorage_GetSkinStatistics_Call) Run(run func(ctx context.Context, skinID uuid.UUID)) *MockSkinStorage_GetSkinStatistics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockSkinStorage_GetSkinStatistics_Call) Return(_a0 *models.SkinStatistics, _a1 error) *MockSkinStorage_GetSkinStatistics_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSkinStorage_GetSkinStatistics_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*models.SkinStatistics, error)) *MockSkinStorage_GetSkinStatistics_Call {
	_c.Call.Return(run)
	return _c
}

// GetSkins provides a mock function with given fields: ctx, filter
func (_m *MockSkinStorage) GetSkins(ctx context.Context, filter *models.SkinFilter) ([]models.Skin, int, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetSkins")
	}

	var r0 []models.Skin
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.SkinFilter) ([]models.Skin, int, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.SkinFilter) []models.Skin); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Skin)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.SkinFilter) int); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *models.SkinFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockSkinStorage_GetSkins_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSkins'
type MockSkinStorage_GetSkins_Call struct {
	*mock.Call
}

// GetSkins is a helper method to define mock.On call
//   - ctx context.Context
//   - filter *models.SkinFilter
func (_e *MockSkinStorage_Expecter) GetSkins(ctx interface{}, filter interface{}) *MockSkinStorage_GetSkins_Call {
	return &MockSkinStorage_GetSkins_Call{Call: _e.mock.On("GetSkins", ctx, filter)}
}

func (_c *MockSkinStorage_GetSkins_Call) Run(run func(ctx context.Context, filter *models.SkinFilter)) *MockSkinStorage_GetSkins_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.SkinFilter))
	})
	return _c
}

func (_c *MockSkinStorage_GetSkins_Call) Return(_a0 []models.Skin, _a1 int, _a2 error) *MockSkinStorage_GetSkins_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockSkinStorage_GetSkins_Call) RunAndReturn(run func(context.Context, *models.SkinFilter) ([]models.Skin, int, error)) *MockSkinStorage_GetSkins_Call {
	_c.Call.Return(run)
	return _c
}

// SearchSkins provides a mock function with given fields: ctx, query, limit
func (_m *MockSkinStorage) SearchSkins(ctx context.Context, query string, limit int) ([]models.Skin, error) {
	ret := _m.Called(ctx, query, limit)

	if len(ret) == 0 {
		panic("no return value specified for SearchSkins")
	}

	var r0 []models.Skin
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) ([]models.Skin, error)); ok {
		return rf(ctx, query, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) []models.Skin); ok {
		r0 = rf(ctx, query, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Skin)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, query, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSkinStorage_SearchSkins_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchSkins'
type MockSkinStorage_SearchSkins_Call struct {
	*mock.Call
}

// SearchSkins is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - limit int
func (_e *MockSkinStorage_Expecter) SearchSkins(ctx interface{}, query interface{}, limit interface{}) *MockSkinStorage_SearchSkins_Call {
	return &MockSkinStorage_SearchSkins_Call{Call: _e.mock.On("SearchSkins", ctx, query, limit)}
}

func (_c *MockSkinStorage_SearchSkins_Call) Run(run func(ctx context.Context, query string, limit int)) *MockSkinStorage_SearchSkins_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *MockSkinStorage_SearchSkins_Call) Return(_a0 []models.Skin, _a1 error) *MockSkinStorage_SearchSkins_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSkinStorage_SearchSkins_Call) RunAndReturn(run func(context.Context, string, int) ([]models.Skin, error)) *MockSkinStorage_SearchSkins_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSkinStorage creates a new instance of MockSkinStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSkinStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSkinStorage {
	mock := &MockSkinStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSkinCache is an autogenerated mock type for the SkinCache type
type MockSkinCache struct {
	mock.Mock
}

type MockSkinCache_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSkinCache) EXPECT() *MockSkinCache_Expecter {
	return &MockSkinCache_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, key
func (_m *MockSkinCache) Get(ctx context.Context, key string) (string, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Set provides a mock function with given fields: ctx, key, value, ttl
func (_m *MockSkinCache) Set(ctx context.Context, key string, value string, ttl time.Duration) error {
	ret := _m.Called(ctx, key, value, ttl)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) error); ok {
		r0 = rf(ctx, key, value, ttl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, key
func (_m *MockSkinCache) Delete(ctx context.Context, key string) error {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetSkinList provides a mock function with given fields: ctx, cacheKey
func (_m *MockSkinCache) GetSkinList(ctx context.Context, cacheKey string) (*models.SkinListResponse, bool) {
	ret := _m.Called(ctx, cacheKey)

	if len(ret) == 0 {
		panic("no return value specified for GetSkinList")
	}

	var r0 *models.SkinListResponse
	var r1 bool
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.SkinListResponse, bool)); ok {
		return rf(ctx, cacheKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.SkinListResponse); ok {
		r0 = rf(ctx, cacheKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.SkinListResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = rf(ctx, cacheKey)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// SetSkinList provides a mock function with given fields: ctx, cacheKey, response, ttl
func (_m *MockSkinCache) SetSkinList(ctx context.Context, cacheKey string, response *models.SkinListResponse, ttl time.Duration) error {
	ret := _m.Called(ctx, cacheKey, response, ttl)

	if len(ret) == 0 {
		panic("no return value specified for SetSkinList")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *models.SkinListResponse, time.Duration) error); ok {
		r0 = rf(ctx, cacheKey, response, ttl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetSkinDetail provides a mock function with given fields: ctx, slug
func (_m *MockSkinCache) GetSkinDetail(ctx context.Context, slug string) (*models.SkinDetailResponse, bool) {
	ret := _m.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for GetSkinDetail")
	}

	var r0 *models.SkinDetailResponse
	var r1 bool
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.SkinDetailResponse, bool)); ok {
		return rf(ctx, slug)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.SkinDetailResponse); ok {
		r0 = rf(ctx, slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.SkinDetailResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = rf(ctx, slug)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// SetSkinDetail provides a mock function with given fields: ctx, slug, response, ttl
func (_m *MockSkinCache) SetSkinDetail(ctx context.Context, slug string, response *models.SkinDetailResponse, ttl time.Duration) error {
	ret := _m.Called(ctx, slug, response, ttl)

	if len(ret) == 0 {
		panic("no return value specified for SetSkinDetail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *models.SkinDetailResponse, time.Duration) error); ok {
		r0 = rf(ctx, slug, response, ttl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockSkinCache creates a new instance of MockSkinCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSkinCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSkinCache {
	mock := &MockSkinCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
