// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: models/skin_model.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SkinModel struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MarketHashName  string                 `protobuf:"bytes,2,opt,name=market_hash_name,json=marketHashName,proto3" json:"market_hash_name,omitempty"`
	Name            string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Weapon          string                 `protobuf:"bytes,4,opt,name=weapon,proto3" json:"weapon,omitempty"`
	Quality         string                 `protobuf:"bytes,5,opt,name=quality,proto3" json:"quality,omitempty"`
	Rarity          string                 `protobuf:"bytes,6,opt,name=rarity,proto3" json:"rarity,omitempty"`
	CurrentPrice    float64                `protobuf:"fixed64,7,opt,name=current_price,json=currentPrice,proto3" json:"current_price,omitempty"`
	Currency        string                 `protobuf:"bytes,8,opt,name=currency,proto3" json:"currency,omitempty"`
	ImageUrl        string                 `protobuf:"bytes,9,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Volume_24H      int32                  `protobuf:"varint,10,opt,name=volume_24h,json=volume24h,proto3" json:"volume_24h,omitempty"`
	PriceChange_24H float64                `protobuf:"fixed64,11,opt,name=price_change_24h,json=priceChange24h,proto3" json:"price_change_24h,omitempty"`
	PriceChange_7D  float64                `protobuf:"fixed64,12,opt,name=price_change_7d,json=priceChange7d,proto3" json:"price_change_7d,omitempty"`
	Slug            string                 `protobuf:"bytes,13,opt,name=slug,proto3" json:"slug,omitempty"`
	CreatedAt       string                 `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       string                 `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SkinModel) Reset() {
	*x = SkinModel{}
	mi := &file_models_skin_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkinModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkinModel) ProtoMessage() {}

func (x *SkinModel) ProtoReflect() protoreflect.Message {
	mi := &file_models_skin_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkinModel.ProtoReflect.Descriptor instead.
func (*SkinModel) Descriptor() ([]byte, []int) {
	return file_models_skin_model_proto_rawDescGZIP(), []int{0}
}

func (x *SkinModel) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SkinModel) GetMarketHashName() string {
	if x != nil {
		return x.MarketHashName
	}
	return ""
}

func (x *SkinModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SkinModel) GetWeapon() string {
	if x != nil {
		return x.Weapon
	}
	return ""
}

func (x *SkinModel) GetQuality() string {
	if x != nil {
		return x.Quality
	}
	return ""
}

func (x *SkinModel) GetRarity() string {
	if x != nil {
		return x.Rarity
	}
	return ""
}

func (x *SkinModel) GetCurrentPrice() float64 {
	if x != nil {
		return x.CurrentPrice
	}
	return 0
}

func (x *SkinModel) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *SkinModel) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *SkinModel) GetVolume_24H() int32 {
	if x != nil {
		return x.Volume_24H
	}
	return 0
}

func (x *SkinModel) GetPriceChange_24H() float64 {
	if x != nil {
		return x.PriceChange_24H
	}
	return 0
}

func (x *SkinModel) GetPriceChange_7D() float64 {
	if x != nil {
		return x.PriceChange_7D
	}
	return 0
}

func (x *SkinModel) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *SkinModel) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *SkinModel) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type SkinDetailModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skin          *SkinModel             `protobuf:"bytes,1,opt,name=skin,proto3" json:"skin,omitempty"`
	Statistics    *SkinStatisticsModel   `protobuf:"bytes,2,opt,name=statistics,proto3" json:"statistics,omitempty"`
	PriceHistory  []*PriceHistoryModel   `protobuf:"bytes,3,rep,name=price_history,json=priceHistory,proto3" json:"price_history,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkinDetailModel) Reset() {
	*x = SkinDetailModel{}
	mi := &file_models_skin_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkinDetailModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkinDetailModel) ProtoMessage() {}

func (x *SkinDetailModel) ProtoReflect() protoreflect.Message {
	mi := &file_models_skin_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkinDetailModel.ProtoReflect.Descriptor instead.
func (*SkinDetailModel) Descriptor() ([]byte, []int) {
	return file_models_skin_model_proto_rawDescGZIP(), []int{1}
}

func (x *SkinDetailModel) GetSkin() *SkinModel {
	if x != nil {
		return x.Skin
	}
	return nil
}

func (x *SkinDetailModel) GetStatistics() *SkinStatisticsModel {
	if x != nil {
		return x.Statistics
	}
	return nil
}

func (x *SkinDetailModel) GetPriceHistory() []*PriceHistoryModel {
	if x != nil {
		return x.PriceHistory
	}
	return nil
}

type SkinStatisticsModel struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AvgPrice_7D     float64                `protobuf:"fixed64,1,opt,name=avg_price_7d,json=avgPrice7d,proto3" json:"avg_price_7d,omitempty"`
	AvgPrice_30D    float64                `protobuf:"fixed64,2,opt,name=avg_price_30d,json=avgPrice30d,proto3" json:"avg_price_30d,omitempty"`
	TotalVolume_7D  int32                  `protobuf:"varint,3,opt,name=total_volume_7d,json=totalVolume7d,proto3" json:"total_volume_7d,omitempty"`
	TotalVolume_30D int32                  `protobuf:"varint,4,opt,name=total_volume_30d,json=totalVolume30d,proto3" json:"total_volume_30d,omitempty"`
	PriceVolatility float64                `protobuf:"fixed64,5,opt,name=price_volatility,json=priceVolatility,proto3" json:"price_volatility,omitempty"`
	MinPrice_7D     float64                `protobuf:"fixed64,6,opt,name=min_price_7d,json=minPrice7d,proto3" json:"min_price_7d,omitempty"`
	MaxPrice_7D     float64                `protobuf:"fixed64,7,opt,name=max_price_7d,json=maxPrice7d,proto3" json:"max_price_7d,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SkinStatisticsModel) Reset() {
	*x = SkinStatisticsModel{}
	mi := &file_models_skin_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkinStatisticsModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkinStatisticsModel) ProtoMessage() {}

func (x *SkinStatisticsModel) ProtoReflect() protoreflect.Message {
	mi := &file_models_skin_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkinStatisticsModel.ProtoReflect.Descriptor instead.
func (*SkinStatisticsModel) Descriptor() ([]byte, []int) {
	return file_models_skin_model_proto_rawDescGZIP(), []int{2}
}

func (x *SkinStatisticsModel) GetAvgPrice_7D() float64 {
	if x != nil {
		return x.AvgPrice_7D
	}
	return 0
}

func (x *SkinStatisticsModel) GetAvgPrice_30D() float64 {
	if x != nil {
		return x.AvgPrice_30D
	}
	return 0
}

func (x *SkinStatisticsModel) GetTotalVolume_7D() int32 {
	if x != nil {
		return x.TotalVolume_7D
	}
	return 0
}

func (x *SkinStatisticsModel) GetTotalVolume_30D() int32 {
	if x != nil {
		return x.TotalVolume_30D
	}
	return 0
}

func (x *SkinStatisticsModel) GetPriceVolatility() float64 {
	if x != nil {
		return x.PriceVolatility
	}
	return 0
}

func (x *SkinStatisticsModel) GetMinPrice_7D() float64 {
	if x != nil {
		return x.MinPrice_7D
	}
	return 0
}

func (x *SkinStatisticsModel) GetMaxPrice_7D() float64 {
	if x != nil {
		return x.MaxPrice_7D
	}
	return 0
}

type PriceHistoryModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SkinId        string                 `protobuf:"bytes,2,opt,name=skin_id,json=skinId,proto3" json:"skin_id,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Source        string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	Volume        int32                  `protobuf:"varint,6,opt,name=volume,proto3" json:"volume,omitempty"`
	RecordedAt    string                 `protobuf:"bytes,7,opt,name=recorded_at,json=recordedAt,proto3" json:"recorded_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceHistoryModel) Reset() {
	*x = PriceHistoryModel{}
	mi := &file_models_skin_model_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceHistoryModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceHistoryModel) ProtoMessage() {}

func (x *PriceHistoryModel) ProtoReflect() protoreflect.Message {
	mi := &file_models_skin_model_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceHistoryModel.ProtoReflect.Descriptor instead.
func (*PriceHistoryModel) Descriptor() ([]byte, []int) {
	return file_models_skin_model_proto_rawDescGZIP(), []int{3}
}

func (x *PriceHistoryModel) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PriceHistoryModel) GetSkinId() string {
	if x != nil {
		return x.SkinId
	}
	return ""
}

func (x *PriceHistoryModel) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *PriceHistoryModel) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *PriceHistoryModel) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *PriceHistoryModel) GetVolume() int32 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *PriceHistoryModel) GetRecordedAt() string {
	if x != nil {
		return x.RecordedAt
	}
	return ""
}

type PriceChartDataModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     string                 `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Price         float64                `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	Volume        int32                  `protobuf:"varint,3,opt,name=volume,proto3" json:"volume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceChartDataModel) Reset() {
	*x = PriceChartDataModel{}
	mi := &file_models_skin_model_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceChartDataModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceChartDataModel) ProtoMessage() {}

func (x *PriceChartDataModel) ProtoReflect() protoreflect.Message {
	mi := &file_models_skin_model_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceChartDataModel.ProtoReflect.Descriptor instead.
func (*PriceChartDataModel) Descriptor() ([]byte, []int) {
	return file_models_skin_model_proto_rawDescGZIP(), []int{4}
}

func (x *PriceChartDataModel) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *PriceChartDataModel) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *PriceChartDataModel) GetVolume() int32 {
	if x != nil {
		return x.Volume
	}
	return 0
}

type MarketOverviewModel struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TotalSkins      int32                  `protobuf:"varint,1,opt,name=total_skins,json=totalSkins,proto3" json:"total_skins,omitempty"`
	AvgPrice        float64                `protobuf:"fixed64,2,opt,name=avg_price,json=avgPrice,proto3" json:"avg_price,omitempty"`
	TotalVolume_24H int32                  `protobuf:"varint,3,opt,name=total_volume_24h,json=totalVolume24h,proto3" json:"total_volume_24h,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MarketOverviewModel) Reset() {
	*x = MarketOverviewModel{}
	mi := &file_models_skin_model_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketOverviewModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketOverviewModel) ProtoMessage() {}

func (x *MarketOverviewModel) ProtoReflect() protoreflect.Message {
	mi := &file_models_skin_model_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketOverviewModel.ProtoReflect.Descriptor instead.
func (*MarketOverviewModel) Descriptor() ([]byte, []int) {
	return file_models_skin_model_proto_rawDescGZIP(), []int{5}
}

func (x *MarketOverviewModel) GetTotalSkins() int32 {
	if x != nil {
		return x.TotalSkins
	}
	return 0
}

func (x *MarketOverviewModel) GetAvgPrice() float64 {
	if x != nil {
		return x.AvgPrice
	}
	return 0
}

func (x *MarketOverviewModel) GetTotalVolume_24H() int32 {
	if x != nil {
		return x.TotalVolume_24H
	}
	return 0
}

type TrendingSkinModel struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Rank            int32                  `protobuf:"varint,1,opt,name=rank,proto3" json:"rank,omitempty"`
	Skin            *SkinModel             `protobuf:"bytes,2,opt,name=skin,proto3" json:"skin,omitempty"`
	PriceChangeRate float64                `protobuf:"fixed64,3,opt,name=price_change_rate,json=priceChangeRate,proto3" json:"price_change_rate,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TrendingSkinModel) Reset() {
	*x = TrendingSkinModel{}
	mi := &file_models_skin_model_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrendingSkinModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrendingSkinModel) ProtoMessage() {}

func (x *TrendingSkinModel) ProtoReflect() protoreflect.Message {
	mi := &file_models_skin_model_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrendingSkinModel.ProtoReflect.Descriptor instead.
func (*TrendingSkinModel) Descriptor() ([]byte, []int) {
	return file_models_skin_model_proto_rawDescGZIP(), []int{6}
}

func (x *TrendingSkinModel) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *TrendingSkinModel) GetSkin() *SkinModel {
	if x != nil {
		return x.Skin
	}
	return nil
}

func (x *TrendingSkinModel) GetPriceChangeRate() float64 {
	if x != nil {
		return x.PriceChangeRate
	}
	return 0
}

var File_models_skin_model_proto protoreflect.FileDescriptor

const file_models_skin_model_proto_rawDesc = "" +
	"\n" +
	"\x17models/skin_model.proto\x12\x0fskins.models.v1\"\xc4\x03\n" +
	"\tSkinModel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12(\n" +
	"\x10market_hash_name\x18\x02 \x01(\tR\x0emarketHashName\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06weapon\x18\x04 \x01(\tR\x06weapon\x12\x18\n" +
	"\aquality\x18\x05 \x01(\tR\aquality\x12\x16\n" +
	"\x06rarity\x18\x06 \x01(\tR\x06rarity\x12#\n" +
	"\rcurrent_price\x18\a \x01(\x01R\fcurrentPrice\x12\x1a\n" +
	"\bcurrency\x18\b \x01(\tR\bcurrency\x12\x1b\n" +
	"\timage_url\x18\t \x01(\tR\bimageUrl\x12\x1d\n" +
	"\n" +
	"volume_24h\x18\n" +
	" \x01(\x05R\tvolume24h\x12(\n" +
	"\x10price_change_24h\x18\v \x01(\x01R\x0epriceChange24h\x12&\n" +
	"\x0fprice_change_7d\x18\f \x01(\x01R\rpriceChange7d\x12\x12\n" +
	"\x04slug\x18\r \x01(\tR\x04slug\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0e \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\tR\tupdatedAt\"\xd0\x01\n" +
	"\x0fSkinDetailModel\x12.\n" +
	"\x04skin\x18\x01 \x01(\v2\x1a.skins.models.v1.SkinModelR\x04skin\x12D\n" +
	"\n" +
	"statistics\x18\x02 \x01(\v2$.skins.models.v1.SkinStatisticsModelR\n" +
	"statistics\x12G\n" +
	"\rprice_history\x18\x03 \x03(\v2\".skins.models.v1.PriceHistoryModelR\fpriceHistory\"\x9c\x02\n" +
	"\x13SkinStatisticsModel\x12 \n" +
	"\favg_price_7d\x18\x01 \x01(\x01R\n" +
	"avgPrice7d\x12\"\n" +
	"\ravg_price_30d\x18\x02 \x01(\x01R\vavgPrice30d\x12&\n" +
	"\x0ftotal_volume_7d\x18\x03 \x01(\x05R\rtotalVolume7d\x12(\n" +
	"\x10total_volume_30d\x18\x04 \x01(\x05R\x0etotalVolume30d\x12)\n" +
	"\x10price_volatility\x18\x05 \x01(\x01R\x0fpriceVolatility\x12 \n" +
	"\fmin_price_7d\x18\x06 \x01(\x01R\n" +
	"minPrice7d\x12 \n" +
	"\fmax_price_7d\x18\a \x01(\x01R\n" +
	"maxPrice7d\"\xbf\x01\n" +
	"\x11PriceHistoryModel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\askin_id\x18\x02 \x01(\tR\x06skinId\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x12\x16\n" +
	"\x06volume\x18\x06 \x01(\x05R\x06volume\x12\x1f\n" +
	"\vrecorded_at\x18\a \x01(\tR\n" +
	"recordedAt\"a\n" +
	"\x13PriceChartDataModel\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x01R\x05price\x12\x16\n" +
	"\x06volume\x18\x03 \x01(\x05R\x06volume\"}\n" +
	"\x13MarketOverviewModel\x12\x1f\n" +
	"\vtotal_skins\x18\x01 \x01(\x05R\n" +
	"totalSkins\x12\x1b\n" +
	"\tavg_price\x18\x02 \x01(\x01R\bavgPrice\x12(\n" +
	"\x10total_volume_24h\x18\x03 \x01(\x05R\x0etotalVolume24h\"\x83\x01\n" +
	"\x11TrendingSkinModel\x12\x12\n" +
	"\x04rank\x18\x01 \x01(\x05R\x04rank\x12.\n" +
	"\x04skin\x18\x02 \x01(\v2\x1a.skins.models.v1.SkinModelR\x04skin\x12*\n" +
	"\x11price_change_rate\x18\x03 \x01(\x01R\x0fpriceChangeRateB1Z/github.com/kedr891/cs-parser/internal/pb/modelsb\x06proto3"

var (
	file_models_skin_model_proto_rawDescOnce sync.Once
	file_models_skin_model_proto_rawDescData []byte
)

func file_models_skin_model_proto_rawDescGZIP() []byte {
	file_models_skin_model_proto_rawDescOnce.Do(func() {
		file_models_skin_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_models_skin_model_proto_rawDesc), len(file_models_skin_model_proto_rawDesc)))
	})
	return file_models_skin_model_proto_rawDescData
}

var file_models_skin_model_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_models_skin_model_proto_goTypes = []any{
	(*SkinModel)(nil),           // 0: skins.models.v1.SkinModel
	(*SkinDetailModel)(nil),     // 1: skins.models.v1.SkinDetailModel
	(*SkinStatisticsModel)(nil), // 2: skins.models.v1.SkinStatisticsModel
	(*PriceHistoryModel)(nil),   // 3: skins.models.v1.PriceHistoryModel
	(*PriceChartDataModel)(nil), // 4: skins.models.v1.PriceChartDataModel
	(*MarketOverviewModel)(nil), // 5: skins.models.v1.MarketOverviewModel
	(*TrendingSkinModel)(nil),   // 6: skins.models.v1.TrendingSkinModel
}
var file_models_skin_model_proto_depIdxs = []int32{
	0, // 0: skins.models.v1.SkinDetailModel.skin:type_name -> skins.models.v1.SkinModel
	2, // 1: skins.models.v1.SkinDetailModel.statistics:type_name -> skins.models.v1.SkinStatisticsModel
	3, // 2: skins.models.v1.SkinDetailModel.price_history:type_name -> skins.models.v1.PriceHistoryModel
	0, // 3: skins.models.v1.TrendingSkinModel.skin:type_name -> skins.models.v1.SkinModel
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_models_skin_model_proto_init() }
func file_models_skin_model_proto_init() {
	if File_models_skin_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_models_skin_model_proto_rawDesc), len(file_models_skin_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_skin_model_proto_goTypes,
		DependencyIndexes: file_models_skin_model_proto_depIdxs,
		MessageInfos:      file_models_skin_model_proto_msgTypes,
	}.Build()
	File_models_skin_model_proto = out.File
	file_models_skin_model_proto_goTypes = nil
	file_models_skin_model_proto_depIdxs = nil
}
