// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: skins_api/skins.proto

package skins_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SkinsService_GetSkins_FullMethodName          = "/skins.service.v1.SkinsService/GetSkins"
	SkinsService_GetSkinBySlug_FullMethodName     = "/skins.service.v1.SkinsService/GetSkinBySlug"
	SkinsService_SearchSkins_FullMethodName       = "/skins.service.v1.SkinsService/SearchSkins"
	SkinsService_GetPopularSkins_FullMethodName   = "/skins.service.v1.SkinsService/GetPopularSkins"
	SkinsService_GetPriceChart_FullMethodName     = "/skins.service.v1.SkinsService/GetPriceChart"
	SkinsService_GetTrending_FullMethodName       = "/skins.service.v1.SkinsService/GetTrending"
	SkinsService_GetMarketOverview_FullMethodName = "/skins.service.v1.SkinsService/GetMarketOverview"
	SkinsService_GetTopGainers_FullMethodName     = "/skins.service.v1.SkinsService/GetTopGainers"
	SkinsService_GetTopLosers_FullMethodName      = "/skins.service.v1.SkinsService/GetTopLosers"
)

// SkinsServiceClient is the client API for SkinsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SkinsServiceClient interface {
	GetSkins(ctx context.Context, in *GetSkinsRequest, opts ...grpc.CallOption) (*GetSkinsResponse, error)
	GetSkinBySlug(ctx context.Context, in *GetSkinBySlugRequest, opts ...grpc.CallOption) (*GetSkinBySlugResponse, error)
	SearchSkins(ctx context.Context, in *SearchSkinsRequest, opts ...grpc.CallOption) (*SearchSkinsResponse, error)
	GetPopularSkins(ctx context.Context, in *GetPopularSkinsRequest, opts ...grpc.CallOption) (*GetPopularSkinsResponse, error)
	GetPriceChart(ctx context.Context, in *GetPriceChartRequest, opts ...grpc.CallOption) (*GetPriceChartResponse, error)
	GetTrending(ctx context.Context, in *GetTrendingRequest, opts ...grpc.CallOption) (*GetTrendingResponse, error)
	GetMarketOverview(ctx context.Context, in *GetMarketOverviewRequest, opts ...grpc.CallOption) (*GetMarketOverviewResponse, error)
	GetTopGainers(ctx context.Context, in *GetTopGainersRequest, opts ...grpc.CallOption) (*GetTopGainersResponse, error)
	GetTopLosers(ctx context.Context, in *GetTopLosersRequest, opts ...grpc.CallOption) (*GetTopLosersResponse, error)
}

type skinsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSkinsServiceClient(cc grpc.ClientConnInterface) SkinsServiceClient {
	return &skinsServiceClient{cc}
}

func (c *skinsServiceClient) GetSkins(ctx context.Context, in *GetSkinsRequest, opts ...grpc.CallOption) (*GetSkinsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSkinsResponse)
	err := c.cc.Invoke(ctx, SkinsService_GetSkins_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skinsServiceClient) GetSkinBySlug(ctx context.Context, in *GetSkinBySlugRequest, opts ...grpc.CallOption) (*GetSkinBySlugResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSkinBySlugResponse)
	err := c.cc.Invoke(ctx, SkinsService_GetSkinBySlug_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skinsServiceClient) SearchSkins(ctx context.Context, in *SearchSkinsRequest, opts ...grpc.CallOption) (*SearchSkinsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchSkinsResponse)
	err := c.cc.Invoke(ctx, SkinsService_SearchSkins_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skinsServiceClient) GetPopularSkins(ctx context.Context, in *GetPopularSkinsRequest, opts ...grpc.CallOption) (*GetPopularSkinsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPopularSkinsResponse)
	err := c.cc.Invoke(ctx, SkinsService_GetPopularSkins_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skinsServiceClient) GetPriceChart(ctx context.Context, in *GetPriceChartRequest, opts ...grpc.CallOption) (*GetPriceChartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPriceChartResponse)
	err := c.cc.Invoke(ctx, SkinsService_GetPriceChart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skinsServiceClient) GetTrending(ctx context.Context, in *GetTrendingRequest, opts ...grpc.CallOption) (*GetTrendingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTrendingResponse)
	err := c.cc.Invoke(ctx, SkinsService_GetTrending_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skinsServiceClient) GetMarketOverview(ctx context.Context, in *GetMarketOverviewRequest, opts ...grpc.CallOption) (*GetMarketOverviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMarketOverviewResponse)
	err := c.cc.Invoke(ctx, SkinsService_GetMarketOverview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skinsServiceClient) GetTopGainers(ctx context.Context, in *GetTopGainersRequest, opts ...grpc.CallOption) (*GetTopGainersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTopGainersResponse)
	err := c.cc.Invoke(ctx, SkinsService_GetTopGainers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skinsServiceClient) GetTopLosers(ctx context.Context, in *GetTopLosersRequest, opts ...grpc.CallOption) (*GetTopLosersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTopLosersResponse)
	err := c.cc.Invoke(ctx, SkinsService_GetTopLosers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SkinsServiceServer is the server API for SkinsService service.
// All implementations must embed UnimplementedSkinsServiceServer
// for forward compatibility.
type SkinsServiceServer interface {
	GetSkins(context.Context, *GetSkinsRequest) (*GetSkinsResponse, error)
	GetSkinBySlug(context.Context, *GetSkinBySlugRequest) (*GetSkinBySlugResponse, error)
	SearchSkins(context.Context, *SearchSkinsRequest) (*SearchSkinsResponse, error)
	GetPopularSkins(context.Context, *GetPopularSkinsRequest) (*GetPopularSkinsResponse, error)
	GetPriceChart(context.Context, *GetPriceChartRequest) (*GetPriceChartResponse, error)
	GetTrending(context.Context, *GetTrendingRequest) (*GetTrendingResponse, error)
	GetMarketOverview(context.Context, *GetMarketOverviewRequest) (*GetMarketOverviewResponse, error)
	GetTopGainers(context.Context, *GetTopGainersRequest) (*GetTopGainersResponse, error)
	GetTopLosers(context.Context, *GetTopLosersRequest) (*GetTopLosersResponse, error)
	mustEmbedUnimplementedSkinsServiceServer()
}

// UnimplementedSkinsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSkinsServiceServer struct{}

func (UnimplementedSkinsServiceServer) GetSkins(context.Context, *GetSkinsRequest) (*GetSkinsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSkins not implemented")
}
func (UnimplementedSkinsServiceServer) GetSkinBySlug(context.Context, *GetSkinBySlugRequest) (*GetSkinBySlugResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSkinBySlug not implemented")
}
func (UnimplementedSkinsServiceServer) SearchSkins(context.Context, *SearchSkinsRequest) (*SearchSkinsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchSkins not implemented")
}
func (UnimplementedSkinsServiceServer) GetPopularSkins(context.Context, *GetPopularSkinsRequest) (*GetPopularSkinsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPopularSkins not implemented")
}
func (UnimplementedSkinsServiceServer) GetPriceChart(context.Context, *GetPriceChartRequest) (*GetPriceChartResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPriceChart not implemented")
}
func (UnimplementedSkinsServiceServer) GetTrending(context.Context, *GetTrendingRequest) (*GetTrendingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTrending not implemented")
}
func (UnimplementedSkinsServiceServer) GetMarketOverview(context.Context, *GetMarketOverviewRequest) (*GetMarketOverviewResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMarketOverview not implemented")
}
func (UnimplementedSkinsServiceServer) GetTopGainers(context.Context, *GetTopGainersRequest) (*GetTopGainersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTopGainers not implemented")
}
func (UnimplementedSkinsServiceServer) GetTopLosers(context.Context, *GetTopLosersRequest) (*GetTopLosersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTopLosers not implemented")
}
func (UnimplementedSkinsServiceServer) mustEmbedUnimplementedSkinsServiceServer() {}
func (UnimplementedSkinsServiceServer) testEmbeddedByValue()                      {}

// UnsafeSkinsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SkinsServiceServer will
// result in compilation errors.
type UnsafeSkinsServiceServer interface {
	mustEmbedUnimplementedSkinsServiceServer()
}

func RegisterSkinsServiceServer(s grpc.ServiceRegistrar, srv SkinsServiceServer) {
	// If the following call panics, it indicates UnimplementedSkinsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SkinsService_ServiceDesc, srv)
}

func _SkinsService_GetSkins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSkinsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkinsServiceServer).GetSkins(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkinsService_GetSkins_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkinsServiceServer).GetSkins(ctx, req.(*GetSkinsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkinsService_GetSkinBySlug_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSkinBySlugRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkinsServiceServer).GetSkinBySlug(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkinsService_GetSkinBySlug_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkinsServiceServer).GetSkinBySlug(ctx, req.(*GetSkinBySlugRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkinsService_SearchSkins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchSkinsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkinsServiceServer).SearchSkins(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkinsService_SearchSkins_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkinsServiceServer).SearchSkins(ctx, req.(*SearchSkinsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkinsService_GetPopularSkins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPopularSkinsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkinsServiceServer).GetPopularSkins(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkinsService_GetPopularSkins_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkinsServiceServer).GetPopularSkins(ctx, req.(*GetPopularSkinsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkinsService_GetPriceChart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPriceChartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkinsServiceServer).GetPriceChart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkinsService_GetPriceChart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkinsServiceServer).GetPriceChart(ctx, req.(*GetPriceChartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkinsService_GetTrending_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrendingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkinsServiceServer).GetTrending(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkinsService_GetTrending_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkinsServiceServer).GetTrending(ctx, req.(*GetTrendingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkinsService_GetMarketOverview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMarketOverviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkinsServiceServer).GetMarketOverview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkinsService_GetMarketOverview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkinsServiceServer).GetMarketOverview(ctx, req.(*GetMarketOverviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkinsService_GetTopGainers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopGainersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkinsServiceServer).GetTopGainers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkinsService_GetTopGainers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkinsServiceServer).GetTopGainers(ctx, req.(*GetTopGainersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkinsService_GetTopLosers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopLosersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkinsServiceServer).GetTopLosers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkinsService_GetTopLosers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkinsServiceServer).GetTopLosers(ctx, req.(*GetTopLosersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SkinsService_ServiceDesc is the grpc.ServiceDesc for SkinsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SkinsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "skins.service.v1.SkinsService",
	HandlerType: (*SkinsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSkins",
			Handler:    _SkinsService_GetSkins_Handler,
		},
		{
			MethodName: "GetSkinBySlug",
			Handler:    _SkinsService_GetSkinBySlug_Handler,
		},
		{
			MethodName: "SearchSkins",
			Handler:    _SkinsService_SearchSkins_Handler,
		},
		{
			MethodName: "GetPopularSkins",
			Handler:    _SkinsService_GetPopularSkins_Handler,
		},
		{
			MethodName: "GetPriceChart",
			Handler:    _SkinsService_GetPriceChart_Handler,
		},
		{
			MethodName: "GetTrending",
			Handler:    _SkinsService_GetTrending_Handler,
		},
		{
			MethodName: "GetMarketOverview",
			Handler:    _SkinsService_GetMarketOverview_Handler,
		},
		{
			MethodName: "GetTopGainers",
			Handler:    _SkinsService_GetTopGainers_Handler,
		},
		{
			MethodName: "GetTopLosers",
			Handler:    _SkinsService_GetTopLosers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "skins_api/skins.proto",
}
