// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: skins_api/skins.proto

package skins_api

import (
	models "github.com/kedr891/cs-parser/internal/pb/models"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSkinsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Weapon        string                 `protobuf:"bytes,1,opt,name=weapon,proto3" json:"weapon,omitempty"`
	Quality       string                 `protobuf:"bytes,2,opt,name=quality,proto3" json:"quality,omitempty"`
	MinPrice      float64                `protobuf:"fixed64,3,opt,name=min_price,json=minPrice,proto3" json:"min_price,omitempty"`
	MaxPrice      float64                `protobuf:"fixed64,4,opt,name=max_price,json=maxPrice,proto3" json:"max_price,omitempty"`
	Search        string                 `protobuf:"bytes,5,opt,name=search,proto3" json:"search,omitempty"`
	SortBy        string                 `protobuf:"bytes,6,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	SortOrder     string                 `protobuf:"bytes,7,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	Page          int32                  `protobuf:"varint,8,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,9,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSkinsRequest) Reset() {
	*x = GetSkinsRequest{}
	mi := &file_skins_api_skins_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSkinsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSkinsRequest) ProtoMessage() {}

func (x *GetSkinsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skins_api_skins_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSkinsRequest.ProtoReflect.Descriptor instead.
func (*GetSkinsRequest) Descriptor() ([]byte, []int) {
	return file_skins_api_skins_proto_rawDescGZIP(), []int{0}
}

func (x *GetSkinsRequest) GetWeapon() string {
	if x != nil {
		return x.Weapon
	}
	return ""
}

func (x *GetSkinsRequest) GetQuality() string {
	if x != nil {
		return x.Quality
	}
	return ""
}

func (x *GetSkinsRequest) GetMinPrice() float64 {
	if x != nil {
		return x.MinPrice
	}
	return 0
}

func (x *GetSkinsRequest) GetMaxPrice() float64 {
	if x != nil {
		return x.MaxPrice
	}
	return 0
}

func (x *GetSkinsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *GetSkinsRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *GetSkinsRequest) GetSortOrder() string {
	if x != nil {
		return x.SortOrder
	}
	return ""
}

func (x *GetSkinsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetSkinsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetSkinsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skins         []*models.SkinModel    `protobuf:"bytes,1,rep,name=skins,proto3" json:"skins,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	TotalPages    int32                  `protobuf:"varint,5,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSkinsResponse) Reset() {
	*x = GetSkinsResponse{}
	mi := &file_skins_api_skins_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSkinsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSkinsResponse) ProtoMessage() {}

func (x *GetSkinsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skins_api_skins_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSkinsResponse.ProtoReflect.Descriptor instead.
func (*GetSkinsResponse) Descriptor() ([]byte, []int) {
	return file_skins_api_skins_proto_rawDescGZIP(), []int{1}
}

func (x *GetSkinsResponse) GetSkins() []*models.SkinModel {
	if x != nil {
		return x.Skins
	}
	return nil
}

func (x *GetSkinsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetSkinsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetSkinsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetSkinsResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

type GetSkinBySlugRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	Period        string                 `protobuf:"bytes,2,opt,name=period,proto3" json:"period,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSkinBySlugRequest) Reset() {
	*x = GetSkinBySlugRequest{}
	mi := &file_skins_api_skins_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSkinBySlugRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSkinBySlugRequest) ProtoMessage() {}

func (x *GetSkinBySlugRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skins_api_skins_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSkinBySlugRequest.ProtoReflect.Descriptor instead.
func (*GetSkinBySlugRequest) Descriptor() ([]byte, []int) {
	return file_skins_api_skins_proto_rawDescGZIP(), []int{2}
}

func (x *GetSkinBySlugRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *GetSkinBySlugRequest) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

type GetSkinBySlugResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Skin          *models.SkinDetailModel `protobuf:"bytes,1,opt,name=skin,proto3" json:"skin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSkinBySlugResponse) Reset() {
	*x = GetSkinBySlugResponse{}
	mi := &file_skins_api_skins_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSkinBySlugResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSkinBySlugResponse) ProtoMessage() {}

func (x *GetSkinBySlugResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skins_api_skins_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSkinBySlugResponse.ProtoReflect.Descriptor instead.
func (*GetSkinBySlugResponse) Descriptor() ([]byte, []int) {
	return file_skins_api_skins_proto_rawDescGZIP(), []int{3}
}

func (x *GetSkinBySlugResponse) GetSkin() *models.SkinDetailModel {
	if x != nil {
		return x.Skin
	}
	return nil
}

type SearchSkinsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchSkinsRequest) Reset() {
	*x = SearchSkinsRequest{}
	mi := &file_skins_api_skins_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchSkinsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchSkinsRequest) ProtoMessage() {}

func (x *SearchSkinsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skins_api_skins_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchSkinsRequest.ProtoReflect.Descriptor instead.
func (*SearchSkinsRequest) Descriptor() ([]byte, []int) {
	return file_skins_api_skins_proto_rawDescGZIP(), []int{4}
}

func (x *SearchSkinsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchSkinsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SearchSkinsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skins         []*models.SkinModel    `protobuf:"bytes,1,rep,name=skins,proto3" json:"skins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchSkinsResponse) Reset() {
	*x = SearchSkinsResponse{}
	mi := &file_skins_api_skins_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchSkinsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchSkinsResponse) ProtoMessage() {}

func (x *SearchSkinsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skins_api_skins_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchSkinsResponse.ProtoReflect.Descriptor instead.
func (*SearchSkinsResponse) Descriptor() ([]byte, []int) {
	return file_skins_api_skins_proto_rawDescGZIP(), []int{5}
}

func (x *SearchSkinsResponse) GetSkins() []*models.SkinModel {
	if x != nil {
		return x.Skins
	}
	return nil
}

type GetPopularSkinsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPopularSkinsRequest) Reset() {
	*x = GetPopularSkinsRequest{}
	mi := &file_skins_api_skins_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPopularSkinsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPopularSkinsRequest) ProtoMessage() {}

func (x *GetPopularSkinsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skins_api_skins_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPopularSkinsRequest.ProtoReflect.Descriptor instead.
func (*GetPopularSkinsRequest) Descriptor() ([]byte, []int) {
	return file_skins_api_skins_proto_rawDescGZIP(), []int{6}
}

func (x *GetPopularSkinsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetPopularSkinsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skins         []*models.SkinModel    `protobuf:"bytes,1,rep,name=skins,proto3" json:"skins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPopularSkinsResponse) Reset() {
	*x = GetPopularSkinsResponse{}
	mi := &file_skins_api_skins_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPopularSkinsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPopularSkinsResponse) ProtoMessage() {}

func (x *GetPopularSkinsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skins_api_skins_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPopularSkinsResponse.ProtoReflect.Descriptor instead.
func (*GetPopularSkinsResponse) Descriptor() ([]byte, []int) {
	return file_skins_api_skins_proto_rawDescGZIP(), []int{7}
}

func (x *GetPopularSkinsResponse) GetSkins() []*models.SkinModel {
	if x != nil {
		return x.Skins
	}
	return nil
}

type GetPriceChartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	Period        string                 `protobuf:"bytes,2,opt,name=period,proto3" json:"period,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPriceChartRequest) Reset() {
	*x = GetPriceChartRequest{}
	mi := &file_skins_api_skins_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPriceChartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPriceChartRequest) ProtoMessage() {}

func (x *GetPriceChartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skins_api_skins_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPriceChartRequest.ProtoReflect.Descriptor instead.
func (*GetPriceChartRequest) Descriptor() ([]byte, []int) {
	return file_skins_api_skins_proto_rawDescGZIP(), []int{8}
}

func (x *GetPriceChartRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *GetPriceChartRequest) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

type GetPriceChartResponse struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	SkinId        string                        `protobuf:"bytes,1,opt,name=skin_id,json=skinId,proto3" json:"skin_id,omitempty"`
	Period        string                        `protobuf:"bytes,2,opt,name=period,proto3" json:"period,omitempty"`
	DataPoints    []*models.PriceChartDataModel `protobuf:"bytes,3,rep,name=data_points,json=dataPoints,proto3" json:"data_points,omitempty"`
	MinPrice      float64                       `protobuf:"fixed64,4,opt,name=min_price,json=minPrice,proto3" json:"min_price,omitempty"`
	MaxPrice      float64                       `protobuf:"fixed64,5,opt,name=max_price,json=maxPrice,proto3" json:"max_price,omitempty"`
	AvgPrice      float64                       `protobuf:"fixed64,6,opt,name=avg_price,json=avgPrice,proto3" json:"avg_price,omitempty"`
	TotalVolume   int32                         `protobuf:"varint,7,opt,name=total_volume,json=totalVolume,proto3" json:"total_volume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPriceChartResponse) Reset() {
	*x = GetPriceChartResponse{}
	mi := &file_skins_api_skins_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPriceChartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPriceChartResponse) ProtoMessage() {}

func (x *GetPriceChartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skins_api_skins_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPriceChartResponse.ProtoReflect.Descriptor instead.
func (*GetPriceChartResponse) Descriptor() ([]byte, []int) {
	return file_skins_api_skins_proto_rawDescGZIP(), []int{9}
}

func (x *GetPriceChartResponse) GetSkinId() string {
	if x != nil {
		return x.SkinId
	}
	return ""
}

func (x *GetPriceChartResponse) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

func (x *GetPriceChartResponse) GetDataPoints() []*models.PriceChartDataModel {
	if x != nil {
		return x.DataPoints
	}
	return nil
}

func (x *GetPriceChartResponse) GetMinPrice() float64 {
	if x != nil {
		return x.MinPrice
	}
	return 0
}

func (x *GetPriceChartResponse) GetMaxPrice() float64 {
	if x != nil {
		return x.MaxPrice
	}
	return 0
}

func (x *GetPriceChartResponse) GetAvgPrice() float64 {
	if x != nil {
		return x.AvgPrice
	}
	return 0
}

func (x *GetPriceChartResponse) GetTotalVolume() int32 {
	if x != nil {
		return x.TotalVolume
	}
	return 0
}

type GetTrendingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Period        string                 `protobuf:"bytes,1,opt,name=period,proto3" json:"period,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrendingRequest) Reset() {
	*x = GetTrendingRequest{}
	mi := &file_skins_api_skins_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrendingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrendingRequest) ProtoMessage() {}

func (x *GetTrendingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skins_api_skins_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrendingRequest.ProtoReflect.Descriptor instead.
func (*GetTrendingRequest) Descriptor() ([]byte, []int) {
	return file_skins_api_skins_proto_rawDescGZIP(), []int{10}
}

func (x *GetTrendingRequest) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

func (x *GetTrendingRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetTrendingResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	TrendingSkins []*models.TrendingSkinModel `protobuf:"bytes,1,rep,name=trending_skins,json=trendingSkins,proto3" json:"trending_skins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrendingResponse) Reset() {
	*x = GetTrendingResponse{}
	mi := &file_skins_api_skins_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrendingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrendingResponse) ProtoMessage() {}

func (x *GetTrendingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skins_api_skins_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrendingResponse.ProtoReflect.Descriptor instead.
func (*GetTrendingResponse) Descriptor() ([]byte, []int) {
	return file_skins_api_skins_proto_rawDescGZIP(), []int{11}
}

func (x *GetTrendingResponse) GetTrendingSkins() []*models.TrendingSkinModel {
	if x != nil {
		return x.TrendingSkins
	}
	return nil
}

type GetMarketOverviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMarketOverviewRequest) Reset() {
	*x = GetMarketOverviewRequest{}
	mi := &file_skins_api_skins_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMarketOverviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMarketOverviewRequest) ProtoMessage() {}

func (x *GetMarketOverviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skins_api_skins_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMarketOverviewRequest.ProtoReflect.Descriptor instead.
func (*GetMarketOverviewRequest) Descriptor() ([]byte, []int) {
	return file_skins_api_skins_proto_rawDescGZIP(), []int{12}
}

type GetMarketOverviewResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Overview      *models.MarketOverviewModel `protobuf:"bytes,1,opt,name=overview,proto3" json:"overview,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMarketOverviewResponse) Reset() {
	*x = GetMarketOverviewResponse{}
	mi := &file_skins_api_skins_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMarketOverviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMarketOverviewResponse) ProtoMessage() {}

func (x *GetMarketOverviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skins_api_skins_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMarketOverviewResponse.ProtoReflect.Descriptor instead.
func (*GetMarketOverviewResponse) Descriptor() ([]byte, []int) {
	return file_skins_api_skins_proto_rawDescGZIP(), []int{13}
}

func (x *GetMarketOverviewResponse) GetOverview() *models.MarketOverviewModel {
	if x != nil {
		return x.Overview
	}
	return nil
}

type GetTopGainersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopGainersRequest) Reset() {
	*x = GetTopGainersRequest{}
	mi := &file_skins_api_skins_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopGainersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopGainersRequest) ProtoMessage() {}

func (x *GetTopGainersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skins_api_skins_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopGainersRequest.ProtoReflect.Descriptor instead.
func (*GetTopGainersRequest) Descriptor() ([]byte, []int) {
	return file_skins_api_skins_proto_rawDescGZIP(), []int{14}
}

func (x *GetTopGainersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetTopGainersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skins         []*models.SkinModel    `protobuf:"bytes,1,rep,name=skins,proto3" json:"skins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopGainersResponse) Reset() {
	*x = GetTopGainersResponse{}
	mi := &file_skins_api_skins_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopGainersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopGainersResponse) ProtoMessage() {}

func (x *GetTopGainersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skins_api_skins_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopGainersResponse.ProtoReflect.Descriptor instead.
func (*GetTopGainersResponse) Descriptor() ([]byte, []int) {
	return file_skins_api_skins_proto_rawDescGZIP(), []int{15}
}

func (x *GetTopGainersResponse) GetSkins() []*models.SkinModel {
	if x != nil {
		return x.Skins
	}
	return nil
}

type GetTopLosersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopLosersRequest) Reset() {
	*x = GetTopLosersRequest{}
	mi := &file_skins_api_skins_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopLosersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopLosersRequest) ProtoMessage() {}

func (x *GetTopLosersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skins_api_skins_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopLosersRequest.ProtoReflect.Descriptor instead.
func (*GetTopLosersRequest) Descriptor() ([]byte, []int) {
	return file_skins_api_skins_proto_rawDescGZIP(), []int{16}
}

func (x *GetTopLosersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetTopLosersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skins         []*models.SkinModel    `protobuf:"bytes,1,rep,name=skins,proto3" json:"skins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopLosersResponse) Reset() {
	*x = GetTopLosersResponse{}
	mi := &file_skins_api_skins_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopLosersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopLosersResponse) ProtoMessage() {}

func (x *GetTopLosersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skins_api_skins_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopLosersResponse.ProtoReflect.Descriptor instead.
func (*GetTopLosersResponse) Descriptor() ([]byte, []int) {
	return file_skins_api_skins_proto_rawDescGZIP(), []int{17}
}

func (x *GetTopLosersResponse) GetSkins() []*models.SkinModel {
	if x != nil {
		return x.Skins
	}
	return nil
}

var File_skins_api_skins_proto protoreflect.FileDescriptor

const file_skins_api_skins_proto_rawDesc = "" +
	"\n" +
	"\x15skins_api/skins.proto\x12\x10skins.service.v1\x1a\x17models/skin_model.proto\x1a\x1cgoogle/api/annotations.proto\"\xfe\x01\n" +
	"\x0fGetSkinsRequest\x12\x16\n" +
	"\x06weapon\x18\x01 \x01(\tR\x06weapon\x12\x18\n" +
	"\aquality\x18\x02 \x01(\tR\aquality\x12\x1b\n" +
	"\tmin_price\x18\x03 \x01(\x01R\bminPrice\x12\x1b\n" +
	"\tmax_price\x18\x04 \x01(\x01R\bmaxPrice\x12\x16\n" +
	"\x06search\x18\x05 \x01(\tR\x06search\x12\x17\n" +
	"\asort_by\x18\x06 \x01(\tR\x06sortBy\x12\x1d\n" +
	"\n" +
	"sort_order\x18\a \x01(\tR\tsortOrder\x12\x12\n" +
	"\x04page\x18\b \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\t \x01(\x05R\bpageSize\"\xac\x01\n" +
	"\x10GetSkinsResponse\x120\n" +
	"\x05skins\x18\x01 \x03(\v2\x1a.skins.models.v1.SkinModelR\x05skins\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\vtotal_pages\x18\x05 \x01(\x05R\n" +
	"totalPages\"B\n" +
	"\x14GetSkinBySlugRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\x12\x16\n" +
	"\x06period\x18\x02 \x01(\tR\x06period\"M\n" +
	"\x15GetSkinBySlugResponse\x124\n" +
	"\x04skin\x18\x01 \x01(\v2 .skins.models.v1.SkinDetailModelR\x04skin\"@\n" +
	"\x12SearchSkinsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"G\n" +
	"\x13SearchSkinsResponse\x120\n" +
	"\x05skins\x18\x01 \x03(\v2\x1a.skins.models.v1.SkinModelR\x05skins\".\n" +
	"\x16GetPopularSkinsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"K\n" +
	"\x17GetPopularSkinsResponse\x120\n" +
	"\x05skins\x18\x01 \x03(\v2\x1a.skins.models.v1.SkinModelR\x05skins\"B\n" +
	"\x14GetPriceChartRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\x12\x16\n" +
	"\x06period\x18\x02 \x01(\tR\x06period\"\x89\x02\n" +
	"\x15GetPriceChartResponse\x12\x17\n" +
	"\askin_id\x18\x01 \x01(\tR\x06skinId\x12\x16\n" +
	"\x06period\x18\x02 \x01(\tR\x06period\x12E\n" +
	"\vdata_points\x18\x03 \x03(\v2$.skins.models.v1.PriceChartDataModelR\n" +
	"dataPoints\x12\x1b\n" +
	"\tmin_price\x18\x04 \x01(\x01R\bminPrice\x12\x1b\n" +
	"\tmax_price\x18\x05 \x01(\x01R\bmaxPrice\x12\x1b\n" +
	"\tavg_price\x18\x06 \x01(\x01R\bavgPrice\x12!\n" +
	"\ftotal_volume\x18\a \x01(\x05R\vtotalVolume\"B\n" +
	"\x12GetTrendingRequest\x12\x16\n" +
	"\x06period\x18\x01 \x01(\tR\x06period\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"`\n" +
	"\x13GetTrendingResponse\x12I\n" +
	"\x0etrending_skins\x18\x01 \x03(\v2\".skins.models.v1.TrendingSkinModelR\rtrendingSkins\"\x1a\n" +
	"\x18GetMarketOverviewRequest\"]\n" +
	"\x19GetMarketOverviewResponse\x12@\n" +
	"\boverview\x18\x01 \x01(\v2$.skins.models.v1.MarketOverviewModelR\boverview\",\n" +
	"\x14GetTopGainersRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"I\n" +
	"\x15GetTopGainersResponse\x120\n" +
	"\x05skins\x18\x01 \x03(\v2\x1a.skins.models.v1.SkinModelR\x05skins\"+\n" +
	"\x13GetTopLosersRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"H\n" +
	"\x14GetTopLosersResponse\x120\n" +
	"\x05skins\x18\x01 \x03(\v2\x1a.skins.models.v1.SkinModelR\x05skins2\xab\t\n" +
	"\fSkinsService\x12h\n" +
	"\bGetSkins\x12!.skins.service.v1.GetSkinsRequest\x1a\".skins.service.v1.GetSkinsResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/api/v1/skins\x12~\n" +
	"\rGetSkinBySlug\x12&.skins.service.v1.GetSkinBySlugRequest\x1a'.skins.service.v1.GetSkinBySlugResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/api/v1/skins/{slug}\x12x\n" +
	"\vSearchSkins\x12$.skins.service.v1.SearchSkinsRequest\x1a%.skins.service.v1.SearchSkinsResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/api/v1/skins/search\x12\x85\x01\n" +
	"\x0fGetPopularSkins\x12(.skins.service.v1.GetPopularSkinsRequest\x1a).skins.service.v1.GetPopularSkinsResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/api/v1/skins/popular\x12\x84\x01\n" +
	"\rGetPriceChart\x12&.skins.service.v1.GetPriceChartRequest\x1a'.skins.service.v1.GetPriceChartResponse\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/api/v1/skins/chart/{slug}\x12~\n" +
	"\vGetTrending\x12$.skins.service.v1.GetTrendingRequest\x1a%.skins.service.v1.GetTrendingResponse\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/api/v1/analytics/trending\x12\x97\x01\n" +
	"\x11GetMarketOverview\x12*.skins.service.v1.GetMarketOverviewRequest\x1a+.skins.service.v1.GetMarketOverviewResponse\")\x82\xd3\xe4\x93\x02#\x12!/api/v1/analytics/market-overview\x12\x87\x01\n" +
	"\rGetTopGainers\x12&.skins.service.v1.GetTopGainersRequest\x1a'.skins.service.v1.GetTopGainersResponse\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/api/v1/analytics/top-gainers\x12\x83\x01\n" +
	"\fGetTopLosers\x12%.skins.service.v1.GetTopLosersRequest\x1a&.skins.service.v1.GetTopLosersResponse\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/api/v1/analytics/top-losersB4Z2github.com/kedr891/cs-parser/internal/pb/skins_apib\x06proto3"

var (
	file_skins_api_skins_proto_rawDescOnce sync.Once
	file_skins_api_skins_proto_rawDescData []byte
)

func file_skins_api_skins_proto_rawDescGZIP() []byte {
	file_skins_api_skins_proto_rawDescOnce.Do(func() {
		file_skins_api_skins_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_skins_api_skins_proto_rawDesc), len(file_skins_api_skins_proto_rawDesc)))
	})
	return file_skins_api_skins_proto_rawDescData
}

var file_skins_api_skins_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_skins_api_skins_proto_goTypes = []any{
	(*GetSkinsRequest)(nil),            // 0: skins.service.v1.GetSkinsRequest
	(*GetSkinsResponse)(nil),           // 1: skins.service.v1.GetSkinsResponse
	(*GetSkinBySlugRequest)(nil),       // 2: skins.service.v1.GetSkinBySlugRequest
	(*GetSkinBySlugResponse)(nil),      // 3: skins.service.v1.GetSkinBySlugResponse
	(*SearchSkinsRequest)(nil),         // 4: skins.service.v1.SearchSkinsRequest
	(*SearchSkinsResponse)(nil),        // 5: skins.service.v1.SearchSkinsResponse
	(*GetPopularSkinsRequest)(nil),     // 6: skins.service.v1.GetPopularSkinsRequest
	(*GetPopularSkinsResponse)(nil),    // 7: skins.service.v1.GetPopularSkinsResponse
	(*GetPriceChartRequest)(nil),       // 8: skins.service.v1.GetPriceChartRequest
	(*GetPriceChartResponse)(nil),      // 9: skins.service.v1.GetPriceChartResponse
	(*GetTrendingRequest)(nil),         // 10: skins.service.v1.GetTrendingRequest
	(*GetTrendingResponse)(nil),        // 11: skins.service.v1.GetTrendingResponse
	(*GetMarketOverviewRequest)(nil),   // 12: skins.service.v1.GetMarketOverviewRequest
	(*GetMarketOverviewResponse)(nil),  // 13: skins.service.v1.GetMarketOverviewResponse
	(*GetTopGainersRequest)(nil),       // 14: skins.service.v1.GetTopGainersRequest
	(*GetTopGainersResponse)(nil),      // 15: skins.service.v1.GetTopGainersResponse
	(*GetTopLosersRequest)(nil),        // 16: skins.service.v1.GetTopLosersRequest
	(*GetTopLosersResponse)(nil),       // 17: skins.service.v1.GetTopLosersResponse
	(*models.SkinModel)(nil),           // 18: skins.models.v1.SkinModel
	(*models.SkinDetailModel)(nil),     // 19: skins.models.v1.SkinDetailModel
	(*models.PriceChartDataModel)(nil), // 20: skins.models.v1.PriceChartDataModel
	(*models.TrendingSkinModel)(nil),   // 21: skins.models.v1.TrendingSkinModel
	(*models.MarketOverviewModel)(nil), // 22: skins.models.v1.MarketOverviewModel
}
var file_skins_api_skins_proto_depIdxs = []int32{
	18, // 0: skins.service.v1.GetSkinsResponse.skins:type_name -> skins.models.v1.SkinModel
	19, // 1: skins.service.v1.GetSkinBySlugResponse.skin:type_name -> skins.models.v1.SkinDetailModel
	18, // 2: skins.service.v1.SearchSkinsResponse.skins:type_name -> skins.models.v1.SkinModel
	18, // 3: skins.service.v1.GetPopularSkinsResponse.skins:type_name -> skins.models.v1.SkinModel
	20, // 4: skins.service.v1.GetPriceChartResponse.data_points:type_name -> skins.models.v1.PriceChartDataModel
	21, // 5: skins.service.v1.GetTrendingResponse.trending_skins:type_name -> skins.models.v1.TrendingSkinModel
	22, // 6: skins.service.v1.GetMarketOverviewResponse.overview:type_name -> skins.models.v1.MarketOverviewModel
	18, // 7: skins.service.v1.GetTopGainersResponse.skins:type_name -> skins.models.v1.SkinModel
	18, // 8: skins.service.v1.GetTopLosersResponse.skins:type_name -> skins.models.v1.SkinModel
	0,  // 9: skins.service.v1.SkinsService.GetSkins:input_type -> skins.service.v1.GetSkinsRequest
	2,  // 10: skins.service.v1.SkinsService.GetSkinBySlug:input_type -> skins.service.v1.GetSkinBySlugRequest
	4,  // 11: skins.service.v1.SkinsService.SearchSkins:input_type -> skins.service.v1.SearchSkinsRequest
	6,  // 12: skins.service.v1.SkinsService.GetPopularSkins:input_type -> skins.service.v1.GetPopularSkinsRequest
	8,  // 13: skins.service.v1.SkinsService.GetPriceChart:input_type -> skins.service.v1.GetPriceChartRequest
	10, // 14: skins.service.v1.SkinsService.GetTrending:input_type -> skins.service.v1.GetTrendingRequest
	12, // 15: skins.service.v1.SkinsService.GetMarketOverview:input_type -> skins.service.v1.GetMarketOverviewRequest
	14, // 16: skins.service.v1.SkinsService.GetTopGainers:input_type -> skins.service.v1.GetTopGainersRequest
	16, // 17: skins.service.v1.SkinsService.GetTopLosers:input_type -> skins.service.v1.GetTopLosersRequest
	1,  // 18: skins.service.v1.SkinsService.GetSkins:output_type -> skins.service.v1.GetSkinsResponse
	3,  // 19: skins.service.v1.SkinsService.GetSkinBySlug:output_type -> skins.service.v1.GetSkinBySlugResponse
	5,  // 20: skins.service.v1.SkinsService.SearchSkins:output_type -> skins.service.v1.SearchSkinsResponse
	7,  // 21: skins.service.v1.SkinsService.GetPopularSkins:output_type -> skins.service.v1.GetPopularSkinsResponse
	9,  // 22: skins.service.v1.SkinsService.GetPriceChart:output_type -> skins.service.v1.GetPriceChartResponse
	11, // 23: skins.service.v1.SkinsService.GetTrending:output_type -> skins.service.v1.GetTrendingResponse
	13, // 24: skins.service.v1.SkinsService.GetMarketOverview:output_type -> skins.service.v1.GetMarketOverviewResponse
	15, // 25: skins.service.v1.SkinsService.GetTopGainers:output_type -> skins.service.v1.GetTopGainersResponse
	17, // 26: skins.service.v1.SkinsService.GetTopLosers:output_type -> skins.service.v1.GetTopLosersResponse
	18, // [18:27] is the sub-list for method output_type
	9,  // [9:18] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_skins_api_skins_proto_init() }
func file_skins_api_skins_proto_init() {
	if File_skins_api_skins_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_skins_api_skins_proto_rawDesc), len(file_skins_api_skins_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_skins_api_skins_proto_goTypes,
		DependencyIndexes: file_skins_api_skins_proto_depIdxs,
		MessageInfos:      file_skins_api_skins_proto_msgTypes,
	}.Build()
	File_skins_api_skins_proto = out.File
	file_skins_api_skins_proto_goTypes = nil
	file_skins_api_skins_proto_depIdxs = nil
}
